spring:
  application:
    name: payment-admin-server

  profiles:
    active: local

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml

  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 32MB

  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
      write-durations-as-timestamps: true
      fail-on-empty-beans: false

  cache:
    type: REDIS
    redis:
      time-to-live: 1h

server:
  port: 48096

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log

--- #################### 接口文档配置 ####################

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: NONE
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  encryptor:
    password: XDV71a+xqStEA3WH

mybatis-plus-join:
  banner: false

spring:
  data:
    redis:
      repositories:
        enabled: false

easy-trans:
  is-enable-global: false

--- #################### 芋道相关配置 ####################

yudao:
  info:
    version: 1.0.0
    base-package: cn.iocoder.yudao.module.payment.admin
  web:
    admin-ui:
      url: http://dashboard.yudao.iocoder.cn
  xss:
    enable: false
    exclude-urls:
      - ${management.endpoints.web.base-path}/**
  swagger:
    title: 支付系统-admin
    description: 支付系统admin层服务
    version: ${yudao.info.version}
  tenant:
    enable: true
    ignore-urls:

debug: false
